### ISSUE TITLE
examples/ramdisk hang when accessing block device

### ISSUE THREAD

**Issue by tasleson** [ublk-org/libublk-rs#13]
The loopback example works.  However, when I try running the ramdisk example, I hang when trying to interact with block device.

```
$ sudo modprobe ublk_drv
$ sudo RUST_BACKTRACE=1 target/debug/examples/ramdisk add 1 128
$ lsblk | grep ublk
ublkb1                                        259:4    0   128M  0 disk

$ sudo dd if=/dev/ublkb1 of=/dev/null bs=512 count=1
Killed
```
The `dd` just hangs and I end up having to kill it.  I would like to use this example for something I'm investigating.  What am I missing?

**Comment by ming1** [comment]
Hello,

I can't reproduce the issue, can you share your kernel version?
and the task stacktrace by the following cmd:

cat /proc/`pidof target/debug/examples/ramdisk`/stack

Follows the logs in my test vm:

[root@ktest-36 libublk]# uname -a
Linux ktest-36 6.8.7-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:34:28 UTC 2024 x86_64 GNU/Linux
[root@ktest-36 libublk]# 
[root@ktest-36 libublk]# cargo run --example ramdisk -- add 1 128
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/examples/ramdisk add 1 128`
[root@ktest-36 libublk]# 
dev id 1: nr_hw_queues 1 queue_depth 128 block size 512 dev_capacity 262144
	max rq size 524288 daemon pid 1575 flags 0x4a state LIVE
	ublkc: 237:1 ublkb: 259:1 owner: 0:0
	queue 0 tid: 1575 affinity(0 1 2 3 4 5 6 7 8 9 10 11)
	target {"dev_size":134217728,"name":"example_ramdisk","type":0}
	target_data null

[root@ktest-36 libublk]# dd if=/dev/ublkb1 of=/dev/null bs=512
262144+0 records in
262144+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 0.11596 s, 1.2 GB/s

**Comment by ming1** [comment]
Finally I can reproduce it by running the example in non-root session.

The reason is that println!() causes the child process panic silently and the child process is created by daemonize::Daemonize::new().

Fix it by always dump device info in current(parent) context, this is also what rublk is doing , and more friendly for test code.

The fixes have been pushed to main branch, feel free to test.

**Comment by tasleson** [comment]
> The fixes have been pushed to main branch, feel free to test.

Yes, it's working for me now, thank you!

```$ 

sudo ./target/debug/examples/ramdisk add 1 128

dev id 1: nr_hw_queues 1 queue_depth 128 block size 512 dev_capacity 262144
	max rq size 524288 daemon pid 187097 flags 0x4a state LIVE
	ublkc: 511:1 ublkb: 259:4 owner: 0:0
	queue 0 tid: 187097 affinity(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15)
	target {"dev_size":134217728,"name":"example_ramdisk","type":0}
	target_data null
$ lsblk
NAME                                          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
zram0                                         252:0    0     8G  0 disk  [SWAP]
nvme0n1                                       259:0    0 953.9G  0 disk  
├─nvme0n1p1                                   259:1    0   600M  0 part  /boot/efi
├─nvme0n1p2                                   259:2    0     1G  0 part  /boot
└─nvme0n1p3                                   259:3    0 952.3G  0 part  
  └─luks-2e54214c-e365-40ec-9ab4-846f1ade02a8 253:0    0 952.3G  0 crypt /var/lib/libvirt/images
                                                                         /home
                                                                         /
ublkb1                                        259:4    0   128M  0 disk  

$ sudo dd if=/dev/ublkb1 of=/dev/null bs=512
262144+0 records in
262144+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 0.165491 s, 811 MB/s
```
